# To create a conda environment from this file, run the following command in Anaconda Prompt. Replace ENV_NAME with the desired name for the new environment.
# conda env create --name ENV_NAME --file local_dev_environment.yml
# 
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - numpy=1.20.3
  - openpyxl=3.0.7
  - pandas=1.4.2
  - pip=21.0.1
  - python=3.8.11
  - click=7.1.2
  - google-auth=2.3.3
  - python-levenshtein=0.12.2
  - pip:
    - streamlit==1.3.1
    - protobuf==3.17.3
    - gsheetsdb==0.1.13
